package generate_selefra_terraform_provider

import (
	"bytes"
	"encoding/json"
	"fmt"
	"github.com/PuerkitoBio/goquery"
	"github.com/go-git/go-git/v5"
	"github.com/selefra/selefra-provider-sdk/terraform/provider"
	"github.com/yezihack/colorlog"
	"math/rand"
	"net/url"
	"os"
	"strings"
	"time"
)

type Config struct {
	Selefra   Selefra   `mapstructure:"selefra"`
	Terraform Terraform `mapstructure:"terraform"`
	Output    Output    `mapstructure:"output"`
}

func (x *Config) IsResourceNeedGenerate(resourceName string) bool {
	if len(x.Terraform.TerraformProvider.Resources) == 0 {
		return true
	}
	// TODO 2022-12-14 17:00:44 convert to set
	for _, allowResourceName := range x.Terraform.TerraformProvider.Resources {
		if allowResourceName == resourceName {
			return true
		}
	}
	return false
}

type Selefra struct {
	ModuleName string `mapstructure:"module-name"`
}

func (x *Selefra) getOrAutoDetectModuleName() string {
	if x.ModuleName != "" {
		return x.ModuleName
	}
	x.ModuleName = x.tryFindGitModuleNameFromGoMod()
	if x.ModuleName == "" {
		x.ModuleName = x.tryFindGitModuleNameFromLocalGitRepo()
	}
	return x.ModuleName
}

func (x *Selefra) tryFindGitModuleNameFromGoMod() string {
	fileBytes, err := os.ReadFile("go.mod")
	if err != nil {
		fileBytes, err = os.ReadFile("../go.mod")
	}
	if err != nil {
		return ""
	}
	split := strings.Split(string(fileBytes), "\n")
	if len(split) < 1 {
		return ""
	}
	split = strings.Split(split[0], " ")
	if len(split) != 2 {
		return ""
	}
	if strings.ToLower(split[0]) != "module" {
		return ""
	}

	return split[1]
}

func (x *Selefra) tryFindGitModuleNameFromLocalGitRepo() string {
	open, err := git.PlainOpen(".git")
	if err != nil {
		open, err = git.PlainOpen(".git")
	}
	if err != nil {
		return ""
	}
	remotes, err := open.Remotes()
	if err != nil {
		return ""
	}
	for _, remote := range remotes {
		for _, gitUrl := range remote.Config().URLs {
			repoUrl := convertGitUrl(gitUrl)
			if x.isOkGitRepoUrl(repoUrl) {
				return repoUrl
			}
		}
	}
	return ""
}

func (x *Selefra) isOkGitRepoUrl(repoUrl string) bool {
	if !strings.HasPrefix(strings.ToLower(repoUrl), "github.com/") {
		return false
	}
	split := strings.Split(repoUrl, "/")
	if len(split) != 3 {
		return false
	}
	return true
}

func convertGitUrl(gitUrl string) string {
	s := strings.ReplaceAll(gitUrl, "git@", "")
	s = strings.ReplaceAll(s, ".git", "")
	s = strings.ReplaceAll(s, ":", "/")
	return s
}

// ------------------------------------------------- --------------------------------------------------------------------

type Terraform struct {
	TerraformProvider TerraformProvider `mapstructure:"provider"`
}

// ------------------------------------------------- --------------------------------------------------------------------

// TerraformProvider Set the based Terraform provider's parameters
type TerraformProvider struct {

	// provider's warehouse
	RepoUrl string `mapstructure:"repo-url"`

	// This parameter is required when the provider starts
	Config string `mapstructure:"config"`

	// Provider executable file
	ExecuteFiles []*provider.TerraformProviderFile `mapstructure:"execute-files"`

	// Resources to be generated. If not set, all resources are generated by default
	Resources []string `mapstructure:"resources"`

	providerName string
}

// IsGithubRepo Determines whether the specified repository is a GitHub repository
func (x *TerraformProvider) IsGithubRepo() (bool, error) {
	parse, err := url.Parse(x.RepoUrl)
	if err != nil {
		return false, err
	}
	return strings.ToLower(parse.Hostname()) == "github.com", nil
}

// RequestGithubReleaseFiles A list of the latest releases from GitHub's repository
func (x *TerraformProvider) RequestGithubReleaseFiles() ([]*provider.TerraformProviderFile, error) {
	// use cache
	if len(x.ExecuteFiles) != 0 {
		return x.ExecuteFiles, nil
	}
	parse, err := url.Parse(x.RepoUrl)
	if err != nil {
		return nil, err
	}
	// Use the GitHub API to request the latest Release of the repository
	targetUrl := "https://api.github.com/repos" + parse.Path + "/releases/latest"
	response := request(targetUrl)
	if response == nil {
		return nil, fmt.Errorf("request github repo latest releases failed")
	}
	r := &GithubLatestReleasesResponse{}
	err = json.Unmarshal(response.Body(), &r)
	if err != nil {
		return nil, fmt.Errorf("github repo latest releases response json unmarshal failed: %s", err.Error())
	}
	// make cache
	x.ExecuteFiles = r.ParseProviderFileSlice()

	colorlog.Info("request github release files %s success, find %d releases files", targetUrl, len(x.ExecuteFiles))

	return x.ExecuteFiles, nil
}

// IsTerraformOfficialProvider Check whether the current provider is an official provider
func (x *TerraformProvider) IsTerraformOfficialProvider() (bool, error) {
	parse, err := url.Parse(x.RepoUrl)
	if err != nil {
		return false, err
	}
	if strings.ToLower(parse.Hostname()) != "github.com" {
		return false, nil
	}
	return strings.HasPrefix(parse.Path, "/hashicorp/"), nil
}

// GetTerraformOfficialProviderFiles Get the official provider executable file list
func (x *TerraformProvider) GetTerraformOfficialProviderFiles() ([]*provider.TerraformProviderFile, error) {

	// use cache
	if len(x.ExecuteFiles) != 0 {
		return x.ExecuteFiles, nil
	}

	// 1. Obtain the latest version of the provider
	providerName := x.ParseProviderName()
	if providerName == "" {
		return nil, fmt.Errorf("can not parse provider name from repo url: %s", x.RepoUrl)
	}
	targetUrl := "https://releases.hashicorp.com/" + providerName
	response := request(targetUrl)
	if response == nil {
		return nil, fmt.Errorf("request terraform releases failed, url = %s", targetUrl)
	}
	document, err := goquery.NewDocumentFromReader(bytes.NewReader(response.Body()))
	if err != nil {
		return nil, fmt.Errorf("goquery parse dom failed, error message = %s, response = %s", err.Error(), response.String())
	}
	latestVersionFilePage := ""
	document.Find("li>a").Each(func(i int, selection *goquery.Selection) {
		href, exists := selection.Attr("href")
		if latestVersionFilePage == "" && exists && !strings.HasPrefix(href, "../") {
			latestVersionFilePage = "https://releases.hashicorp.com" + href
		}
	})
	colorlog.Info("Terraform provider %s, find latest version %s", x.ParseProviderName(), latestVersionFilePage)
	// Random hibernation to avoid too frequent requests to Terraform's official repository
	time.Sleep(time.Second * time.Duration(rand.Intn(3)+3))

	// 2. Obtain the file of the latest version
	response = request(latestVersionFilePage)
	if response == nil {
		return nil, fmt.Errorf("request terraform releases failed, url = %s", latestVersionFilePage)
	}
	document, err = goquery.NewDocumentFromReader(bytes.NewReader(response.Body()))
	if err != nil {
		return nil, fmt.Errorf("goquery parse dom failed, error message = %s, response = %s", err.Error(), response.String())
	}
	providerFileSlice := make([]*provider.TerraformProviderFile, 0)
	document.Find("a[data-product]").Each(func(i int, selection *goquery.Selection) {
		version, _ := selection.Attr("data-version")
		os, _ := selection.Attr("data-os")
		arch, _ := selection.Attr("data-arch")
		downloadUrl, _ := selection.Attr("href")
		providerFileSlice = append(providerFileSlice, &provider.TerraformProviderFile{
			ProviderVersion: version,
			DownloadUrl:     downloadUrl,
			Arch:            arch,
			OS:              os,
		})
	})

	// make cache
	x.ExecuteFiles = providerFileSlice

	colorlog.Info("request Terraform provider %s releases success, find %d releases files", x.ParseProviderName(), len(x.ExecuteFiles))

	if len(x.ExecuteFiles) == 0 {
		colorlog.Error(response.String())
	}

	return providerFileSlice, nil
}

// ParseProviderName Resolve the provider name from the repository url
func (x *TerraformProvider) ParseProviderName() string {
	if x.providerName != "" {
		return x.providerName
	}
	split := strings.Split(strings.Trim(x.RepoUrl, "/"), "/")
	if len(split) == 0 {
		return ""
	}
	x.providerName = split[len(split)-1]
	return x.providerName
}

func (x *TerraformProvider) ParseProviderShortName() string {
	return strings.ReplaceAll(x.ParseProviderName(), "terraform-provider-", "")
}

// ------------------------------------------------- --------------------------------------------------------------------

// Output Set output parameters
type Output struct {

	// The directory to which the generated results are output
	Directory string `mapstructure:"directory"`
}

func (x *Output) getDirectoryOrDefault() string {
	if x.Directory == "" {
		x.Directory = "./"
	}
	return x.Directory
}

// ------------------------------------------------- --------------------------------------------------------------------

type GithubLatestReleasesResponse struct {
	URL       string `json:"url"`
	AssetsURL string `json:"assets_url"`
	UploadURL string `json:"upload_url"`
	HTMLURL   string `json:"html_url"`
	ID        int    `json:"id"`
	Author    struct {
		Login             string `json:"login"`
		ID                int    `json:"id"`
		NodeID            string `json:"node_id"`
		AvatarURL         string `json:"avatar_url"`
		GravatarID        string `json:"gravatar_id"`
		URL               string `json:"url"`
		HTMLURL           string `json:"html_url"`
		FollowersURL      string `json:"followers_url"`
		FollowingURL      string `json:"following_url"`
		GistsURL          string `json:"gists_url"`
		StarredURL        string `json:"starred_url"`
		SubscriptionsURL  string `json:"subscriptions_url"`
		OrganizationsURL  string `json:"organizations_url"`
		ReposURL          string `json:"repos_url"`
		EventsURL         string `json:"events_url"`
		ReceivedEventsURL string `json:"received_events_url"`
		Type              string `json:"type"`
		SiteAdmin         bool   `json:"site_admin"`
	} `json:"author"`
	NodeID          string    `json:"node_id"`
	TagName         string    `json:"tag_name"`
	TargetCommitish string    `json:"target_commitish"`
	Name            string    `json:"name"`
	Draft           bool      `json:"draft"`
	Prerelease      bool      `json:"prerelease"`
	CreatedAt       time.Time `json:"created_at"`
	PublishedAt     time.Time `json:"published_at"`
	Assets          []struct {
		URL      string `json:"url"`
		ID       int    `json:"id"`
		NodeID   string `json:"node_id"`
		Name     string `json:"name"`
		Label    string `json:"label"`
		Uploader struct {
			Login             string `json:"login"`
			ID                int    `json:"id"`
			NodeID            string `json:"node_id"`
			AvatarURL         string `json:"avatar_url"`
			GravatarID        string `json:"gravatar_id"`
			URL               string `json:"url"`
			HTMLURL           string `json:"html_url"`
			FollowersURL      string `json:"followers_url"`
			FollowingURL      string `json:"following_url"`
			GistsURL          string `json:"gists_url"`
			StarredURL        string `json:"starred_url"`
			SubscriptionsURL  string `json:"subscriptions_url"`
			OrganizationsURL  string `json:"organizations_url"`
			ReposURL          string `json:"repos_url"`
			EventsURL         string `json:"events_url"`
			ReceivedEventsURL string `json:"received_events_url"`
			Type              string `json:"type"`
			SiteAdmin         bool   `json:"site_admin"`
		} `json:"uploader"`
		ContentType        string    `json:"content_type"`
		State              string    `json:"state"`
		Size               int       `json:"size"`
		DownloadCount      int       `json:"download_count"`
		CreatedAt          time.Time `json:"created_at"`
		UpdatedAt          time.Time `json:"updated_at"`
		BrowserDownloadURL string    `json:"browser_download_url"`
	} `json:"assets"`
	TarballURL string `json:"tarball_url"`
	ZipballURL string `json:"zipball_url"`
	Body       string `json:"body"`
}

// ParseProviderFileSlice The corresponding download file is parsed from the GitHub API response
func (x *GithubLatestReleasesResponse) ParseProviderFileSlice() []*provider.TerraformProviderFile {
	providerFileSlice := make([]*provider.TerraformProviderFile, 0)
	osSet, archSet := getGoAllowArchAndOS()
	for _, assert := range x.Assets {
		os, arch := tryFindOsAndArch(assert.Name, osSet, archSet)
		if os == "" || arch == "" {
			continue
		}
		providerFileSlice = append(providerFileSlice, &provider.TerraformProviderFile{
			ProviderVersion: x.Name,
			DownloadUrl:     assert.BrowserDownloadURL,
			OS:              os,
			Arch:            arch,
		})
	}
	return providerFileSlice
}

// Try to identify the operating system and arch from the file name, if it contains
func tryFindOsAndArch(name string, osSet, archSet map[string]struct{}) (os string, arch string) {
	wordRightIndex := -1
	inWord := false
	for index := len(name) - 1; index >= 0; index-- {
		c := name[index]
		isWordChar := (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') || (c >= '0' && c <= '9')
		if isWordChar && !inWord {
			// find word end
			inWord = true
			wordRightIndex = index + 1
		} else if !isWordChar && inWord {
			// find word begin
			inWord = false
			word := name[index+1 : wordRightIndex]
			if _, exists := osSet[word]; exists && os == "" {
				os = word
			} else if _, exists := archSet[word]; exists && arch == "" {
				arch = word
			}
		}
	}
	// ignore the left border, think no possible
	return
}

// All operating systems and platforms supported by Go
func getGoAllowArchAndOS() (osSet map[string]struct{}, archSet map[string]struct{}) {
	s := `aix/ppc64
android/386    
android/amd64  
android/arm    
android/arm64  
darwin/amd64   
darwin/arm64   
dragonfly/amd64
freebsd/386    
freebsd/amd64  
freebsd/arm    
freebsd/arm64  
illumos/amd64  
ios/amd64      
ios/arm64      
js/wasm        
linux/386      
linux/amd64    
linux/arm      
linux/arm64
linux/loong64
linux/mips
linux/mips64
linux/mips64le
linux/mipsle
linux/ppc64
linux/ppc64le
linux/riscv64
linux/s390x
netbsd/386
netbsd/amd64
netbsd/arm
netbsd/arm64
openbsd/386
openbsd/amd64
openbsd/arm
openbsd/arm64
openbsd/mips64
plan9/386
plan9/amd64
plan9/arm
solaris/amd64
windows/386
windows/amd64
windows/arm
windows/arm64
`
	osSet = make(map[string]struct{}, 0)
	archSet = make(map[string]struct{}, 0)
	for _, item := range strings.Split(s, "\n") {
		split := strings.Split(item, "/")
		if len(split) != 2 {
			continue
		}
		os := strings.TrimSpace(split[0])
		arch := strings.TrimSpace(split[1])
		osSet[os] = struct{}{}
		archSet[arch] = struct{}{}
	}
	return osSet, archSet
}

// ------------------------------------------------- --------------------------------------------------------------------
