// Code generated by https://github.com/selefra/selefra-terraform-provider-scaffolding DO NOT EDIT.
package schema_gen

import (
	"context"
	"github.com/selefra/selefra-provider-sdk/provider/schema"
	"{{.ModuleName}}/client"
	"{{.ModuleName}}/schema_custom"
	"{{.ModuleName}}/schema_manager"
	"github.com/selefra/selefra-provider-sdk/table_schema_generator"{{range $key, $value := .ImportSlice}}
    "{{$key}}" {{end}}
)

func init() {
	generator := &{{.TableSchemaGeneratorName}}{}
	schema_manager.RegisterTable(generator.GetTableName(), generator)
}

type {{.TableSchemaGeneratorName}} struct {
}

var _ table_schema_generator.TableSchemaGenerator = &{{.TableSchemaGeneratorName}}{}

func (x *{{.TableSchemaGeneratorName}}) GetTableName() string {
	return "{{.TableName}}"
}

func (x *{{.TableSchemaGeneratorName}}) GetTableDescription() string {
    terraformDescription := "{{.Description}}"
    customDescription := schema_custom.CustomDescription_{{.TableName}}()
    if customDescription != "" {
        return customDescription
    } else {
        return terraformDescription
    }
}

func (x *{{.TableSchemaGeneratorName}}) GetVersion() uint64 {
	return schema_custom.Version_{{.TableName}}()
}

func (x *{{.TableSchemaGeneratorName}}) GetOptions() *schema.TableOptions {
	options := &schema.TableOptions{ {{if .PrimaryKeys}}
        PrimaryKeys: []string{ {{range $index, $value := .PrimaryKeys}}
                "{{$value}}", {{end}}
            },{{end}}
        }
    schema_custom.CustomOptions_{{.TableName}}(options)
    return options
}

func (x *{{.TableSchemaGeneratorName}}) GetDataSource() *schema.DataSource {
	return &schema.DataSource{
		Pull: func(ctx context.Context, clientMeta *schema.ClientMeta, taskClient any, task *schema.DataSourcePullTask, resultChannel chan<- any) *schema.Diagnostics {
            diagnostics := schema.NewDiagnostics()
            ids, d := schema_custom.ListIds_{{.TableName}}(ctx, clientMeta, taskClient, task, resultChannel)
            if diagnostics.AddDiagnostics(d).HasError() {
                return diagnostics
            }
            if len(ids) == 0 {
                return nil
            }
            bridge := taskClient.(*client.Client).TerraformBridge
            return bridge.ListByIds(ctx, "{{.TableName}}", ids, clientMeta, taskClient, task, resultChannel)
		},
	}
}

func (x *{{.TableSchemaGeneratorName}}) GetExpandClientTask() func(ctx context.Context, clientMeta *schema.ClientMeta, taskClient any, task *schema.DataSourcePullTask) []*schema.ClientTaskContext {
    return schema_custom.Expand_{{.TableName}}()
}

func (x *{{.TableSchemaGeneratorName}}) GetColumns() []*schema.Column {
	// terraform's columns
	columns := []*schema.Column{ {{range $index, $value := .ColumnSchemaSlice}}
        table_schema_generator.NewColumnBuilder().ColumnName("{{$value.ColumnName}}").ColumnType({{$value.ColumnTypeCodeString}}){{if $value.Options.Unique}}.SetUnique(){{end}}{{if $value.Options.NotNull}}.SetNotNull(){{end}}{{if $value.Description}}.Description("{{$value.Description}}"){{end}}{{if $value.ExtractorInlineCodeString}}.
        Extractor({{$value.ExtractorInlineCodeString}}){{end}}.Build(), {{end}}
    }
    // Custom additional columns
    columns = append(columns, schema_custom.CustomExtraColumns_{{.TableName}}()...)
    return columns
}

func (x *{{.TableSchemaGeneratorName}}) GetSubTables() []*schema.Table {
	tables, err := schema_manager.FindTables(schema_custom.SubTables_{{.TableName}}())
	if err != nil {
		panic(err)
	}
	return tables
}
