// Automatically generated by https://github.com/selefra/selefra-terraform-provider-scaffolding, do not edit!
package {{.PackageName}}

import (
	"context"
	"github.com/selefra/selefra-provider-sdk/provider/schema"
	"{{.GoModuleName}}/client"
	"github.com/selefra/selefra-provider-sdk/table_schema_generator"{{range $key, $value := .ImportSlice}}
    "{{$key}}" {{end}}
)

type {{.TableSchemaGeneratorName}} struct {
}

var _ table_schema_generator.TableSchemaGenerator = &{{.TableSchemaGeneratorName}}{}

func (x *{{.TableSchemaGeneratorName}}) GetTableName() string {
	return "{{.TableName}}"
}

func (x *{{.TableSchemaGeneratorName}}) GetTableDescription() string {
	return "{{.Description}}"
}

func (x *{{.TableSchemaGeneratorName}}) GetVersion() uint64 {
	return 0
}

func (x *{{.TableSchemaGeneratorName}}) GetOptions() *schema.TableOptions {
	return &schema.TableOptions{ {{if .PrimaryKeys}}
        PrimaryKeys: []string{ {{range $index, $value := .PrimaryKeys}}
                "{{$value}}", {{end}}
            },{{end}}
        }
}

func (x *{{.TableSchemaGeneratorName}}) GetDataSource() *schema.DataSource {
	return &schema.DataSource{
		Pull: func(ctx context.Context, clientMeta *schema.ClientMeta, taskClient any, task *schema.DataSourcePullTask, resultChannel chan<- any) *schema.Diagnostics {
            diagnostics := schema.NewDiagnostics()
            ids, d := {{.TableName}}_list(ctx, clientMeta, taskClient, task, resultChannel)
            if diagnostics.AddDiagnostics(d).HasError() {
                return diagnostics
            }
            if len(ids) == 0 {
                return nil
            }
            bridge := taskClient.(*client.Client).TerraformBridge
            return bridge.ListByIds(ctx, "{{.TableName}}", ids, clientMeta, taskClient, task, resultChannel)
		},
	}
}

func (x *{{.TableSchemaGeneratorName}}) GetExpandClientTask() func(ctx context.Context, clientMeta *schema.ClientMeta, taskClient any, task *schema.DataSourcePullTask) []*schema.ClientTaskContext {
    // TODO If your provider involves multiple accounts, or multiple regions, specify the logic to extend to multiple tasks here
    return nil
}

func (x *{{.TableSchemaGeneratorName}}) GetColumns() []*schema.Column {
	return []*schema.Column{ {{range $index, $value := .ColumnSchemaSlice}}
        table_schema_generator.NewColumnBuilder().ColumnName("{{$value.ColumnName}}").ColumnType({{$value.ColumnTypeCodeString}}){{if $value.Options.Unique}}.SetUnique(){{end}}{{if $value.Options.NotNull}}.SetNotNull(){{end}}{{if $value.Description}}.Description("{{$value.Description}}"){{end}}{{if $value.ExtractorInlineCodeString}}.
        Extractor({{$value.ExtractorInlineCodeString}}){{end}}.Build(), {{end}}
    }
}

func (x *{{.TableSchemaGeneratorName}}) GetSubTables() []*schema.Table {
    // TODO Specify the dependencies of child tables, if any
    return nil
}
